#注册中心配置
server:
  port: 8889
#服务名字
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#git 仓库的地址
          uri: https://gitee.com/huangyangjiazu/config-server.git
#git 仓库的账号密码
          username: 415079372@qq.com
          password: Huang135133
#加入注册中心，实现高可用
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8888/eureka/