eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8769
spring:
  application:
    name: server-zuul
zuul:
  routes:
    api-a:
      path: /api-member/**
      service-id: server-member
    api-b:
      path: /api-order/**
      service-id: server-order